### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/git2-rs#272]
I compiled with ````ASAN_OPTIONS=detect_odr_violation=0  RUSTFLAGS="-Z sanitizer=address"    cargo test   --target x86_64-unknown-linux-gnu```` and this was found:

````
=================================================================
==9004==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 17 byte(s) in 1 object(s) allocated from:
    #0 0x55fb12b66d5b in strdup /checkout/src/libcompiler_builtins/compiler-rt/lib/asan/asan_interceptors.cc:550
    #1 0x55fb12a64ad4 in git__strdup /tmp/git2-rs/libgit2-sys/libgit2/src/util.h:176:14
    #2 0x55fb12a635e0 in submodule_read_config /tmp/git2-rs/libgit2-sys/libgit2/src/submodule.c:1783:13
    #3 0x55fb12a601c3 in git_submodule_reload /tmp/git2-rs/libgit2-sys/libgit2/src/submodule.c:1506:12
    #4 0x55fb12a5fcb9 in git_submodule_lookup /tmp/git2-rs/libgit2-sys/libgit2/src/submodule.c:226:15
    #5 0x55fb12873395 in git2::repo::Repository::submodules::append::h5e59b986b490b6c2 /tmp/git2-rs/src/repo.rs:663
    #6 0x55fb12a612c7 in git_submodule_foreach /tmp/git2-rs/libgit2-sys/libgit2/src/submodule.c:574:16
    #7 0x55fb12872bf2 in git2::repo::Repository::submodules::hefd23bb2ca79a432 /tmp/git2-rs/src/repo.rs:650
    #8 0x55fb1292b8f5 in git2::submodule::tests::smoke::hd08644eb334b550d /tmp/git2-rs/src/submodule.rs:286
    #9 0x55fb12acd2f1 in test::run_test::{{closure}} /checkout/src/libtest/lib.rs:1510
    #10 0x55fb12acd2f1 in core::ops::function::FnOnce::call_once<closure,(())> /checkout/src/libcore/ops/function.rs:223
    #11 0x55fb12acd2f1 in _ZN42_$LT$F$u20$as$u20$test..FnBox$LT$T$GT$$GT$8call_box17hcf27f4bdcffba6a4E.llvm.6287DFAC /checkout/src/libtest/lib.rs:142
    #12 0x55fb12cb0aee in __rust_maybe_catch_panic /checkout/src/libpanic_unwind/lib.rs:101
    #13 0x55fb12ae3702 in std::panicking::try<(),std::panic::AssertUnwindSafe<closure>> /checkout/src/libstd/panicking.rs:459
    #14 0x55fb12ae3702 in std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()> /checkout/src/libstd/panic.rs:365
    #15 0x55fb12ae3702 in test::run_test::run_test_inner::{{closure}} /checkout/src/libtest/lib.rs:1447
    #16 0x55fb12ae3702 in std::sys_common::backtrace::__rust_begin_short_backtrace::hd75ce7bf3a1f2cc0 /checkout/src/libstd/sys_common/backtrace.rs:133
    #17 0x55fb12ae8dc2 in std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()> /checkout/src/libstd/thread/mod.rs:406
    #18 0x55fb12ae8dc2 in std::panic::{{impl}}::call_once<(),closure> /checkout/src/libstd/panic.rs:300
    #19 0x55fb12ae8dc2 in _ZN3std9panicking3try7do_call17h2cc2ffa7955d3b45E.llvm.E0299BFC /checkout/src/libstd/panicking.rs:480
    #20 0x55fb12cb0aee in __rust_maybe_catch_panic /checkout/src/libpanic_unwind/lib.rs:101
    #21 0x55fb12ad9ced in std::panicking::try<(),std::panic::AssertUnwindSafe<closure>> /checkout/src/libstd/panicking.rs:459
    #22 0x55fb12ad9ced in std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()> /checkout/src/libstd/panic.rs:365
    #23 0x55fb12ad9ced in std::thread::{{impl}}::spawn::{{closure}}<closure,()> /checkout/src/libstd/thread/mod.rs:405
    #24 0x55fb12ad9ced in _ZN50_$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$8call_box17h01b99192f098311fE.llvm.DA84EF27 /checkout/src/liballoc/boxed.rs:825
    #25 0x55fb12c94a3b in alloc::boxed::{{impl}}::call_once<(),()> /checkout/src/liballoc/boxed.rs:835
    #26 0x55fb12c94a3b in std::sys_common::thread::start_thread /checkout/src/libstd/sys_common/thread.rs:24
    #27 0x55fb12c94a3b in _ZN3std3sys4unix6thread6Thread3new12thread_start17h903409d36062ec7bE.llvm.50F603A7 /checkout/src/libstd/sys/unix/thread.rs:90
    #28 0x7f1b6239d739 in start_thread (/lib64/libpthread.so.0+0x7739)
````

**Comment by alexcrichton** [comment]
Maybe a bug in libgit2? This doesn't seem obviously fixable in Rust :(

**Comment by matthiaskrgr** [comment]
I could narrow it down to
````
submodule::tests::smoke
````
or
````
ASAN_OPTIONS=detect_odr_violation=0 RUSTFLAGS="-Z sanitizer=address" cargo test --target x86_64-unknown-linux-gnu  submodule::tests::smoke
````

**Comment by alexcrichton** [comment]
I'm going to close this for now since it's likely an issue with libgit2 rather than these bindings.
