### ISSUE TITLE
HTTPS clone fails "failed to create locked file"

### ISSUE THREAD

**Issue by DazWilkin** [rust-lang/git2-rs#545]
I'm attempting to clone a public GitHub repo using HTTPS with this crate but it fails consistently with "failed to create a locked file" (`./.git/objects/pack/pack_git2_??idx.lock`).

I am able to clone the repo with the crate using SSH without issue and I am able to clone other public repos using HTTPS with the crate without this issue.

I can clone the repo using git from the command-line without issue.

The issue *may* be an issue with the repo itself but I hope you don't mind my starting here.

The repo is: https://github.com/googleapis/googleapis

I (think I'd) prefer to use HTTPS over SSH to avoid having to determine whether a developer has an appropriate SSH key.

It includes protobuf definitions that I want to compile to rust sources. I could copy the protobuf files from the repo but then I'd need to ensure these remain current. The repo only has one, very old release (I may pester the repo maintainers to address this).

I have

`Cargo.toml`:
```TOML
[build-dependencies]
git2 = "0.13.1"
```
and, `build.rs`:
```rust
use git2::Repository;
use std::path::Path;

fn main() {
    Repository::clone(
        "https://github.com/googleapis/googleapis.git",
        Path::new("googleapis"),
    )
    .expect("failed to clone");
}
```
Then:
```bash
rm -rf googleapis && RUST_BACKTRACE=full cargo build
```
yields:
```
error: failed to run custom build command for `rust-googleapis v0.0.1 ...)`

Caused by:
  process didn't exit successfully: `.../rust-googleapis-5e2ade9935306d67/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'failed to clone: Error { code: -1, klass: 2, message: "failed to create locked file \'.../googleapis/.git/objects/pack/pack_git2_V7idx.lock\': No such file or directory" }', build.rs:7:5
stack backtrace:
   0:     0x55f536e9d9f4 - backtrace::backtrace::libunwind::trace::h90669f559fb267f0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x55f536e9d9f4 - backtrace::backtrace::trace_unsynchronized::hffde4e353d8f2f9a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x55f536e9d9f4 - std::sys_common::backtrace::_print_fmt::heaf44068b7eaaa6a
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x55f536e9d9f4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h88671019cf081de2
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55f536eb4bbc - core::fmt::write::h4e6a29ee6319c9fd
                               at src/libcore/fmt/mod.rs:1052
   5:     0x55f536e9c0a7 - std::io::Write::write_fmt::hf06b1c86d898d7d6
                               at src/libstd/io/mod.rs:1426
   6:     0x55f536e9fa55 - std::sys_common::backtrace::_print::h404ff5f2b50cae09
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55f536e9fa55 - std::sys_common::backtrace::print::hcc4377f1f882322e
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55f536e9fa55 - std::panicking::default_hook::{{closure}}::hc172eff6f35b7f39
                               at src/libstd/panicking.rs:204
   9:     0x55f536e9f741 - std::panicking::default_hook::h7a68887d113f8029
                               at src/libstd/panicking.rs:224
  10:     0x55f536ea006a - std::panicking::rust_panic_with_hook::hb7ad5693188bdb00
                               at src/libstd/panicking.rs:472
  11:     0x55f536e9fc50 - rust_begin_unwind
                               at src/libstd/panicking.rs:380
  12:     0x55f536eb4081 - core::panicking::panic_fmt::hb1f3e14b86a3520c
                               at src/libcore/panicking.rs:85
  13:     0x55f536eb3ea3 - core::option::expect_none_failed::he6711468044f7162
                               at src/libcore/option.rs:1199
  14:     0x55f536d7a324 - core::result::Result<T,E>::expect::h4c10db74e6230bd2
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/result.rs:991
  15:     0x55f536d7a3dd - build_script_build::main::h1717712d879eea63
                               at .../build.rs:7
  16:     0x55f536d7a970 - std::rt::lang_start::{{closure}}::h2960548c9cc248a7
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  17:     0x55f536e9fb83 - std::rt::lang_start_internal::{{closure}}::hb26e39676675046f
                               at src/libstd/rt.rs:52
  18:     0x55f536e9fb83 - std::panicking::try::do_call::he4701ab6e48d80c0
                               at src/libstd/panicking.rs:305
  19:     0x55f536ea1787 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  20:     0x55f536ea0510 - std::panicking::try::hd3de25f3cb7024b8
                               at src/libstd/panicking.rs:281
  21:     0x55f536ea0510 - std::panic::catch_unwind::h86c02743a24e3d92
                               at src/libstd/panic.rs:394
  22:     0x55f536ea0510 - std::rt::lang_start_internal::h9cf8802361ad86c2
                               at src/libstd/rt.rs:51
  23:     0x55f536d7a949 - std::rt::lang_start::h63c74eb79bc462a5
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  24:     0x55f536d7a42a - main
  25:     0x7f67ab0eb1e3 - __libc_start_main
  26:     0x55f536d7a1ae - _start
  27:                0x0 - <unknown>
```

If I use the SSH [example](https://docs.rs/git2/0.13.1/git2/build/struct.RepoBuilder.html#example) from the crate documentation, the clone works. Alternatively if I `git clone ...`, this works too.

In both cases, there is no lock file (remaining) in `./.git/objects/pack` but there exist `.idx` and `.pack` files. The latter is ~150MB

**Comment by DazWilkin** [comment]
I think this is my error.

I'm using Visual Studio Code and I realize that the `build.rs` is triggered if, for example, I delete `./target`. If I stick with Visual Studio, delete the cloned repo directories and then delete `./target`, Visual Studio Code reruns `build.rs`, clones the repo (without error) and the build succeeds.
