### ISSUE TITLE
Deadlock while cloning and network dropped

### ISSUE THREAD

**Issue by P3GLEG** [rust-lang/git2-rs#590]
I ran into a deadlock issue if the network connectivity is dropped while you are cloning.

In the code below using parts from the example directory. I set the repo to a known large git repository, and purposefully disconnect my network connection. The callback is then never able to progress and you are unable to recover once connectivity is resumed. I performed a `tcpdump` and waited to see if maybe stdout was broken but resumed downloading; No packets were captured.

I was able to get the program to panic once ( line 90 was RepoBuilder::new() ), no backtrace was enable at the time :(

```bash
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -1, klass: 12, message: "error sending data: Broken pipe" }', src/main.rs:90:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Tested on both Ubuntu 20.04 and Mac Catalina.

Packages: 
git2: 0.13.6
libgit2-sys-0.12.7+1.0.0

```rust
use git2::build::{CheckoutBuilder, RepoBuilder};
use git2::{FetchOptions, Progress, RemoteCallbacks};
use std::cell::RefCell;
use std::io::{self, Write};
use std::path::{Path, PathBuf};



struct State {
    progress: Option<Progress<'static>>,
    total: usize,
    current: usize,
    path: Option<PathBuf>,
    newline: bool,
}

fn print(state: &mut State) {
    let stats = state.progress.as_ref().unwrap();
    let network_pct = (100 * stats.received_objects()) / stats.total_objects();
    let index_pct = (100 * stats.indexed_objects()) / stats.total_objects();
    let co_pct = if state.total > 0 {
        (100 * state.current) / state.total
    } else {
        0
    };
    let kbytes = stats.received_bytes() / 1024;
    if stats.received_objects() == stats.total_objects() {
        if !state.newline {
            println!();
            state.newline = true;
        }
        print!(
            "Resolving deltas {}/{}\r",
            stats.indexed_deltas(),
            stats.total_deltas()
        );
    } else {
        print!(
            "net {:3}% ({:4} kb, {:5}/{:5})  /  idx {:3}% ({:5}/{:5})  \
             /  chk {:3}% ({:4}/{:4}) {}\r",
            network_pct,
            kbytes,
            stats.received_objects(),
            stats.total_objects(),
            index_pct,
            stats.indexed_objects(),
            stats.total_objects(),
            co_pct,
            state.current,
            state.total,
            state
                .path
                .as_ref()
                .map(|s| s.to_string_lossy().into_owned())
                .unwrap_or_default()
        )
    }
    io::stdout().flush().unwrap();
}



fn main() {
    let state = RefCell::new(State {
        progress: None,
        total: 0,
        current: 0,
        path: None,
        newline: false,
    });
    let mut cb = RemoteCallbacks::new();
    cb.transfer_progress(|stats| {
        let mut state = state.borrow_mut();
        state.progress = Some(stats.to_owned());
        print(&mut *state);
        true
    });

    let mut co = CheckoutBuilder::new();
    co.progress(|path, cur, total| {
        let mut state = state.borrow_mut();
        state.path = path.map(|p| p.to_path_buf());
        state.current = cur;
        state.total = total;
        print(&mut *state);
    });

    let mut fo = FetchOptions::new();
    fo.remote_callbacks(cb);
    RepoBuilder::new()
        .fetch_options(fo)
        .with_checkout(co)
        .clone("https://github.com/torvalds/Linux", Path::new("/tmp/linux")).unwrap();
    println!();
}

```

**Comment by alexcrichton** [comment]
It doesn't look like much is happening on the Rust side of things, so perhaps this is a bug in libgit2 itself? Are you able to get backtraces of the deadlocked threads?

**Comment by P3GLEG** [comment]
The ability to trigger a backtrace appears random. I was able to capture one after about 6 tries. So, it's strange if you lose network connectivity and re-enable it within about ~45 seconds it can resume. However, sometimes after waiting about a minute and reconnecting it will hang. I disabled network connectivity, waited 1 minute, then re-enabled it and waited 15 minutes. It just hung. 

<pre><code>
at 07/16/20-11:17:53 in locking on  master [?] is 📦 v0.1.0 via 𝗥 v1.44.1 took 3m 23s
[I]   ./target/debug/locking
^Ct   3% (111476 kb, 226003/7491079)  /  idx   2% (198211/7491079)  /  chk   0% (   0/   0)

✘130
at 07/16/20-11:33:35 in locking on  master [?] is 📦 v0.1.0 via 𝗥 v1.44.1 took <b>15m 23s</b>
[I] 

</pre></code>



```bash
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -1, klass: 12, message: "error sending data: Broken pipe" }', src/main.rs:90:5
stack backtrace:
   0:        0x10319728f - backtrace::backtrace::libunwind::trace::hdff08984d375d02a
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:        0x10319728f - backtrace::backtrace::trace_unsynchronized::h1a393bcdfc10be62
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:        0x10319728f - std::sys_common::backtrace::_print_fmt::h063c5f96b3f1deaf
                               at src/libstd/sys_common/backtrace.rs:78
   3:        0x10319728f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8ad47541fb823094
                               at src/libstd/sys_common/backtrace.rs:59
   4:        0x1031b2a0e - core::fmt::write::he23e9bd6497f06c3
                               at src/libcore/fmt/mod.rs:1069
   5:        0x1031959c7 - std::io::Write::write_fmt::h91528f1131e6004e
                               at src/libstd/io/mod.rs:1504
   6:        0x10319903a - std::sys_common::backtrace::_print::ha16b452b57f4cc4c
                               at src/libstd/sys_common/backtrace.rs:62
   7:        0x10319903a - std::sys_common::backtrace::print::hdcfe7b1cd849140e
                               at src/libstd/sys_common/backtrace.rs:49
   8:        0x10319903a - std::panicking::default_hook::{{closure}}::h1983f014a45a477e
                               at src/libstd/panicking.rs:198
   9:        0x103198d7c - std::panicking::default_hook::hb0d9b93b5be8b120
                               at src/libstd/panicking.rs:218
  10:        0x1031995a8 - std::panicking::rust_panic_with_hook::h9f3faafe0983de5c
                               at src/libstd/panicking.rs:511
  11:        0x103199172 - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  12:        0x1031b70df - core::panicking::panic_fmt::h0a2d1b3ca0b14316
                               at src/libcore/panicking.rs:111
  13:        0x1031b6fe5 - core::option::expect_none_failed::haea18d6ed867f4e9
                               at src/libcore/option.rs:1268
  14:        0x10306578e - core::result::Result<T,E>::unwrap::hfee3c24dc70ee861
                               at /Users/pegleg/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/result.rs:1005
  15:        0x103068f08 - test_lock::main::h2e0e0f0f7ed01b71
                               at src/main.rs:90
  16:        0x103065c4e - std::rt::lang_start::{{closure}}::hdf8e076fec382b51
                               at /Users/pegleg/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/rt.rs:67
  17:        0x103199909 - std::rt::lang_start_internal::{{closure}}::hcd3fdb11e5e01a21
                               at src/libstd/rt.rs:52
  18:        0x103199909 - std::panicking::try::do_call::hd8e8ada4e26d8788
                               at src/libstd/panicking.rs:331
  19:        0x103199909 - std::panicking::try::hf951a93b7ea92f92
                               at src/libstd/panicking.rs:274
  20:        0x103199909 - std::panic::catch_unwind::he82f6de4bcfc0f8c
                               at src/libstd/panic.rs:394
  21:        0x103199909 - std::rt::lang_start_internal::h795af50241e12334
                               at src/libstd/rt.rs:51
  22:        0x103065c31 - std::rt::lang_start::hc38ffb9acafa7644
                               at /Users/pegleg/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/rt.rs:67
  23:        0x103069042 - main
```

I ran git clone from cli, in order to compare. (Not a fair one but kinda close) If you disconnect, it can resume. If you leave it in the hung state after 9 mins and 18 seconds with no network connectivity it dies. 

<pre><code>
at 07/16/20-10:42:34 in /tmp took 4m 9s
[I]   git clone https://github.com/torvalds/linux
Cloning into 'linux'...
remote: Enumerating objects: 7491079, done.
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

✘128
at 07/16/20-11:44:23 in /tmp took <b>9m 18s</b>
</pre></code>

**Comment by P3GLEG** [comment]
As an additional test left one on for a 12 hours, internet was periodically enabled/disabled. 

```bash
at 07/16/20-4:12:42 in locking on  master [?] is 📦 v0.1.0 via 𝗥 v1.44.1
[I]   ./target/debug/locking
^Ct   2% (75354 kb, 150824/7491079)  /  idx   1% (132382/7491079)  /  chk   0% (   0/   0)

✘130
at 07/16/20-16:50:22 in locking on  master [?] is 📦 v0.1.0 via 𝗥 v1.44.1 took 12h 37m 39s
[I] 
```

**Comment by alexcrichton** [comment]
I think these are probably bugs in libgit2 to report? It doesn't look like thi sis an issue with the Rust bindings?

**Comment by P3GLEG** [comment]
No worries, I have created a new issue there .
https://github.com/libgit2/libgit2/issues/5585#issue-659739210

**Comment by P3GLEG** [comment]
It was in libgit. Someone else has since caught it and can be found at https://github.com/libgit2/libgit2/pull/5600.

Cheers for the library man!
